selected_provider: 0
current_model: gemma4:31b
current_mode: chat
current_role: voiceAssistant
current_story: dax_dr_ren
active_scenes: []
active_characters:
    - 4
    - 1
    - 6
num_ctx: 8192
nothink: false
voice: false
voice_speed: 2
